### ISSUE TITLE
sf-client autocompletion of UUID's does not

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#103]
sf-client CLI autocomplete lists the available UUID's (when appropriate) but does not select them to the command line.

**Comment by mikalstill** [comment]
Have you done this in your terminal?

```
eval "$(_SF_CLIENT_COMPLETE=source sf-client)"
```

**Comment by mandoonandy** [comment]
Yes, I have activated the auto-completion. The auto complete is working fine for defined command words. The problem is the lack of auto-completion of dynamic UUID's (as specified above). 

Commit 3eab9c7 in pull request #102 is a partial fix to actually retrieve the UUID's rather than dump with an exception.

Tab completion will display the UUID's with the above commit, but does not select them to the command line.
