### ISSUE TITLE
API Endpoints do not conform to POST/PUT standardisation

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#117]
Is the endpoint API the best design?

Currently:
**POST auth/namespace/\<namespace>/metadata/<key>**  creates a key

Would it be more appropriate:
**POST auth/namespace/\<namespace>/metadata**  creates a key
**PUT auth/namespace/\<namespace>/metadata/\<key>**  creates or updates a key

Doesn't add functionality, only polish.

**Comment by mikalstill** [comment]
I am not opposed. I mostly just made stuff up as I went along.

**Comment by mandoonandy** [comment]
LOL
