### ISSUE TITLE
Cannot start instances on openstack (CityCloud)

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#146]
Instances do not start in OpenStack hosted clusters (tested on CityCloud). Nothing logged in console data for the instance.

**Comment by mandoonandy** [comment]
root@andy-200711-quoh2ooy-sf-1:~# kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

**Comment by mikalstill** [comment]
Do you have an existing cluster I can take a look at? I'd probably start by grepping /var/log/syslog on sf-1 with the instance's uuid. Its possible libvirt is logging a start error?

**Comment by mandoonandy** [comment]
You can stand one up using:
```
SKIP_SF_TESTS='skippy' BOOTDELAY=60 OS_SSH_KEY_NAME=and-arwen OS_FLAVOR_NAME=2C-4GB-50GB OS_EXTERNAL_NET_NAME="ext-net"  ./deployandtest.sh openstack
```
(Don't forget the ssh key buried in the middle)

**Comment by mikalstill** [comment]
Cannot duplicate.
