### ISSUE TITLE
sf-client show allow namespaces more

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#158]
I'm thinking of things like "instance list" and "network list" mostly.

**Comment by mandoonandy** [comment]
Could you expand on this?

**Comment by mikalstill** [comment]
Sorry, it was a quick note. So, I want to be able to create an instance in a namespace like this:

```
sf-client instance create foo 1 1024 -d 8@cirros -n ... --namespace banana
```

Instead of having to muck around with auth. If I am in the system namespace I should be allowed to impersonate.

**Comment by mandoonandy** [comment]
You can already. 
```sf-client instance create --namespace tim bob2 1 1024 -d 8```

**Comment by mandoonandy** [comment]
@mikalstill  Are you thinking of a different requirement that isn't satisfied by the current ```--namespace``` parameter or can we close this issue?

**Comment by mikalstill** [comment]
I need to remember to be honest. Let's close this and I'll file something more specific if I ever remember what I meant.
