### ISSUE TITLE
The powerstates of instances are not exposed

### ISSUE THREAD

**Issue by LudvikGalois** [shakenfist/shakenfist#159]
Currently the only method of determining the powerstate of an instance is to look at the event log (and even then, that's not entirely accurate for a real-time response). From a usability perspective, this seems to be incompatible with allowing instances to be powered off.

**Comment by mikalstill** [comment]
This is definitely a gap in SF right now. In fact, SF doesn't know the power state of a VM. It knows what power state it attempted to set the instance to (the event log), but it doesn't know if that power state was actually achieved -- think soft power off with an instance which ignores ACPI events. This is definitely something we should rectify.
