### ISSUE TITLE
Remove stray networks

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#161]
daemons/net.py  line 51: remove stray networks

**Comment by mandoonandy** [comment]
Did this get fixed by @mikalstill ?

**Comment by mikalstill** [comment]
No, I do stray instances at the moment, but not stray networks.

**Comment by mikalstill** [comment]
Commit be3a61a1a728c13c7d87bcc05c7ad94928219aaf adds some more logging for this when merged.
