### ISSUE TITLE
Instances can only use cirrus video cards

### ISSUE THREAD

**Issue by LudvikGalois** [shakenfist/shakenfist#201]
The Shakenfist domain xml template has hardcoded the use of a video adapter with type `cirrus`. Whilst this is convenient because it will work with nearly every operating system imaginable, it limits the resolution to 1280x1024. It would be nice to be able set the type to `vga` to allow higher resolutions. (I think that's the libvirt equivalent of `-vga std` on qemu, but I'm not 100% sure)

**Comment by LudvikGalois** [comment]
Being able to set the type to `virtio` for instances with the virtio video drivers would also be nice

**Comment by mikalstill** [comment]
We should let users specify at least model and amount of VRAM.
