### ISSUE TITLE
Libvirt connections don't have matching closes

### ISSUE THREAD

**Issue by Reillytf** [shakenfist/shakenfist#204]
https://github.com/shakenfist/shakenfist/blob/d599ec1e1720292c924583c757a48ce433709556/shakenfist/virt.py#L436

https://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Connections.html#idp21649120 recommends we close connection objects once done with them. I think we should do that thing unless the class going out of Scope fixes the problem for us.

**Comment by mandoonandy** [comment]
This is a good idea rather than relying on the garbage collector. It could make a difference under high loads?

**Comment by mikalstill** [comment]
I'm concerned with doing this for a point release because there is a risk that we will close a connection that we have handed to someone else... We need to be confident that we've shaken out any errors in a way which is probably too hard for a minor release?

**Comment by mandoonandy** [comment]
I agree. Moved to minor release v0.3.
