### ISSUE TITLE
Set up CI running SF

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#214]
We need to be able to dogfood changes without affecting the prod SYD-SF cluster.

The always mentioned CI on SF is probably a priority now. Can we use the CBR hardware or use a cloud?

**Comment by mikalstill** [comment]
We can use CBR or SYD for this without problems. CBR is probably a safer place for experimental things though. The part I don't really have a plan for is how to wire in events from github, but even if we start with kicking it off manually its better than what we have now.

Oh, and we need to make the nextgen CI not completely flakey as well, I've kind of punted on that recently and need to get back to it.

**Comment by mikalstill** [comment]
This has been done for a while now.
