### ISSUE TITLE
Delete-all on networks

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#217]
I am thinking the delete-all API endpoint should continue deleting networks after finding an "in use" network.

Currently upon finding an "in use" network it aborts, reasoning the user doesn't know what they are doing.

There is the current situation where a bug stops one network being deleted. It is not obvious which network it is. I'm now thinking that users might just want to do a lazy delete networks not in use. This also surfaces the network that is supposedly "in use".

Proposal: that ```DELETE /networks``` continues deleting networks after finding an "in use" network.

Thoughts?

**Comment by mikalstill** [comment]
I think that makes sense. Or, it does a scan before doing any deleting and aborts any deletes if there is an in use network, but that would be super prone to race conditions. Option 1 seems simpler and therefore better.
