### ISSUE TITLE
Testing against different python version compared to Ubuntu 18.04

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#222]
Testing is done in python 3.7
Ubuntu 18.04 installs python 3.6

Discuss.

**Comment by mikalstill** [comment]
Sounds like something we could cover with our repeated unit tests in CI? We could run each iteration with a slightly different version of python?

**Comment by mikalstill** [comment]
I think this is resolved now?

**Comment by mandoonandy** [comment]
Agree. CI pipeline tests 3.7 and 3.8
