### ISSUE TITLE
Cleanup events on upgrade

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#283]
Given our errors in past releases, we should probably just delete all instance and network events as part of the upgrade to v0.3. That should probably involve a big warning to the admin that we're doing that.

**Comment by mandoonandy** [comment]
Cleaner deletes all events for a particular network/instance during hard deletion. Deleting events for existing networks/instances would lose real information.

Given that deleting all networks/instances will result in Cleaner eventually deleting the events, I propose not doing anything during the v0.3 upgrade.
