### ISSUE TITLE
Convert snapshot to queue task

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#437]
* Create queue task
* Convert callers
* New API endpoint: list snapshots
* New API endpoint: snapshot status (none, creating, created)

@mikalstill What was the original intent of this line? https://github.com/shakenfist/shakenfist/blob/2ac7d210c5b047e217e6d7729d5f399b23c4d845/shakenfist/external_api/app.py#L849

**Comment by mikalstill** [comment]
That like is amazing... I wonder if it's a search and replace gone wrong?

**Comment by mikalstill** [comment]
Should we have a fetch snapshot API call as well? Do we want to stream gigabytes of data via the rest API? Probably not?

**Comment by mandoonandy** [comment]
We could have fetch. It does make sense.

Extra endpoints:
* Fetch snapshot
* Delete snapshot

**Comment by mandoonandy** [comment]
Git tells me that curious line used to be
```
snap['created'] = snap['created'].timestamp()
```

**Comment by mikalstill** [comment]
Le huh. I am concerned about gunicorn timeouts while serving snapshots. I wonder if those apply if we're doing IO? We only have ten workers per node at the moment IIRC.
