### ISSUE TITLE
Modify image fetching to reduce instance start time

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#480]
Recorded operation `fetch image` takes 1-2 secs due to internet access. This could be avoided since most users don't need (or want) the latest nightly build.

Many options, but first thought is: 
 `A flag to specify "download latest" (ie. current behaviour), and default behaviour is to use currently cached image.`

**Comment by mikalstill** [comment]
I think this is effectively what labels have become. You can add a label to your one true version, and then not download unless you really want to. This is how CI images work now.
