### ISSUE TITLE
Revisit In-memory object memory

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#506]
Multi-step operations on objects - particularly Networks - require that the object be locked to avoid other processes modifying the object. In particular, the API daemon needs to be prevented from deleting the object. Or better still, the other daemons need to reduce their in-memory object hold time and regularly check the network has not been deleted.

This is mostly a problem on the Network node but scenarios can be imagined where queued tasks on a hypervisor node collide with the same hypervisor node directly receiving a network delete API command.

A careful audit of all Network operations is required. The conversion of the Network class to become similar to the Image class will help.

 (I think this should be a priority before further work occurs on fixing inbound network connections.)

**Comment by mikalstill** [comment]
I feel like the non-volatile objects work addresses this. It isn't complete, but the high points have been met and I think its safe to close this while we work through the rest of the transition.
