### ISSUE TITLE
Frequent failures to tear down CI test networks

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#652]
They generally look like this:

```
shakenfist_ci.tests.test_state_changes.TestStateChanges.test_lifecycle_events
-----------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/tmp/workspace/shakenfist_pr_PR-630/deploy/shakenfist_ci/base.py", line 238, in tearDown
    self.test_client.delete_network(net['uuid'])

      File "/usr/local/lib/python3.6/dist-packages/shakenfist_client/apiclient.py", line 334, in delete_network
    '/networks/' + network_uuid)

      File "/usr/local/lib/python3.6/dist-packages/shakenfist_client/apiclient.py", line 162, in _request_url
    return self._actual_request_url(method, url, data=data)

      File "/usr/local/lib/python3.6/dist-packages/shakenfist_client/apiclient.py", line 134, in _actual_request_url
    'API request failed', method, url, r.status_code, r.text)

    shakenfist_client.apiclient.ResourceCannotBeDeletedException: ('API request failed', 'DELETE', 'http://sf-1:13000/networks/bc3eddf6-98c3-4db6-ae3a-3382a8653cc0', 403, '{"error": "you cannot delete an in use network", "status": 403}')
```

More debugging required.

**Comment by mandoonandy** [comment]
Once cause for this might #650. If the delete command is sent before instance creation is finished then the instance is never deleted.

PR #651 *might* be part of the solution.

**Comment by mikalstill** [comment]
This is happening even with an explicit check that all the instances on that network are in the deleted state first. The test in the code is if there are _interfaces_ still for that network. I'll add an explicit check for that in a new patch now.

**Comment by mandoonandy** [comment]
Interfaces are marked deleted when an instance object delete()'s itself. This occurs when the `DeleteInstanceTask` is processed on the queue.

If an API call to delete a network occurs immediately after an instance delete call, the queue daemon may not have processed the delete task. Thus the network delete fails.

The `shakenfist_ci.tests.test_cache_image.TestCacheImage.test_instance_invalid_image` test case regularly fails. It creates an instance with a bad image URL. The test cleanup then deletes the network. This fails since the queues daemon hasn't had time to delete instance.

Since this is the clean up function and not the actual test. I would suggest retrying over a few seconds, it is just a processing delay.

**Comment by mikalstill** [comment]
But the tearDown that does the delete now checks the instance is deleted first...

```
    def tearDown(self):
        super(BaseNamespacedTestCase, self).tearDown()
        for inst in self.test_client.get_instances():
            self.test_client.delete_instance(inst['uuid'])

        start_time = time.time()
        while time.time() - start_time < 300:
            if not list(self.test_client.get_instances()):
                break
            time.sleep(5)

        remaining_instances = list(self.test_client.get_instances())
        if remaining_instances:
            self.fail('Failed to delete instances: %s'
                      % ', '.join(remaining_instances))

        for net in self.test_client.get_networks():
            self.test_client.delete_network(net['uuid'])
        self._remove_namespace(self.namespace)
```

So we shouldn't get as far as calling the delete on the network if there is a still an instance with a state other than deleted or error. Or am I confused?

**Comment by mikalstill** [comment]
Here's a log message which might help...

```
Jan 14 03:40:09 sfci-nzu2wp INFO gunicorn: worker [sf-api][2998] Blocks network delete; network_interface=0b946164-bba1-4134-b030-717bde90c806; state=initial
Jan 14 03:40:09 sfci-nzu2wp INFO gunicorn: worker [sf-api][2998] Returning API error: 403, you cannot delete an in use network
Jan 14 03:40:09 localhost gunicorn.sf.access: [2998] 127.0.0.1 - - [14/Jan/2021:03:40:09 +0000] "DELETE /networks/ed1afbea-56f9-438f-9eef-8277b3d720ad HTTP/1.1" 403 63 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1"

...

Jan 14 03:40:15 sfci-nzu2wp INFO sf-net[2941] Hard deleted stray network interface; instance=8c593e79-c2f6-42ec-b06e-4f414f946f4e; networkinterface=0b946164-bba1-4134-b030-717bde90c806
```

Why is that interface in the initial state? Unfortunately we don't log when we allocate network interfaces, so its a bit hard to tell...
